# fly.toml file generated for trail-progress on 2022-09-28T13:17:18+01:00

app = "trail-progress"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
strategy = "rolling"

[env]
POSTGRES_LISTEN_CHANNEL = "processing"
PROCESSOR_BATCH_SIZE = "20"
PROCESSOR_CONCURRENCY = "2"
PROCESSOR_INTERVAL = "1h"
STRAVA_CLIENT_ID = "79710"
STRAVA_CALLBACK_URL = "https://trail-progress.fly.dev"

[experimental]
allowed_public_ports = []
auto_rollback = true

[[services]]
internal_port = 8080
protocol = "tcp"
[[services.ports]]
handlers = ["http"]
port = 80
force_https = true
[[services.ports]]
handlers = ["tls", "http"]
port = "443"
[[services.tcp_checks]]
grace_period = "1s"
interval = "15s"
restart_limit = 0
timeout = "2s"
